### PR TITLE
AuthenticationTest: Add Active Directory support

### PR DESCRIPTION
**Pull request by antoniotorresm**
Add Active Directory support to AuthenticationTest. This will create a
Windows Server host and deploy Active Directory server on it. After
that, test users are created into AD and trust is established with the
IPA server.

The pamtest tool is also updated to support launching threads for
authenticating Active Directory users.

Signed-off-by: Antonio Torres <antorres@redhat.com>

### CODE REVIEW

**Comment by antoniotorresm** [comment]
To select number of AD logins, the `ad-threads` option is available. This should be equal or less than `threads`. For example, if `threads` is 10 and `ad-threads` is 4, pamtest will execute 4 AD logins and 6 regular IPA logins.

For running the AuthenticationTest during review, change the `ANSIBLE_AUTHENTICATIONTEST_CLIENT_CONFIG_PLAYBOOK` playbook so that it points to https://copr.fedorainfracloud.org/coprs/antorres/freeipa-perftest/, since this COPR repo contains the updated `freeipa-perftest-client` package.

**Comment by rcritten** [comment]
Installation is failing, I think, because the windowsadserver instance isn't being started.

It fails at src/ipaperftest/plugins/authenticationtest.py:108 with a KeyError for 'windowsadserver' in self.hosts. It contains only The 'server' IP.

Vagrant status shows windowsadserver as 'not created'

**Comment by antoniotorresm** [comment]
What is the output of `vagrant up`?
Forgot to mention that two Vagrant plugins need to be installed: `winrm` and `winrm-elevated`. I added these to the README.

**Comment by rcritten** [comment]
I was in the process of doing that :-) It looks like it came up ok manually.

I installed the two plugins based on the mention in the README.

I re-ran the scritp again, capturing the output. It failed because the checksum didn't match expectations. I'm not sure why it worked manually. I'll try again now that the image, I think, is cached locally.

**Comment by rcritten** [comment]
With a proper image I was able to get a complete run but 100% of the AD logins failed.

The trust setup failed with "Cannot find specified domain or server name"

**Comment by rcritten** [comment]
To get it to work on my system I had to add ```ipaserver_no_dnssec_validation=yes``` to ```src/ipaperftest/core/constants.py``` in ```[ipaserver:vars]```

It always fails for me when I use the freeipa copr but but passes when I use yours for some reason. I haven't figure out why yet.

**Comment by antoniotorresm** [comment]
Ok, enabled the `ipaserver_no_dnssec_validation` option.

The reason why it fails when using the freeipa copr is because it doesn't have the updated `pamtest` yet (which contains the `ad-threads` option), but mine does. Once this is merged the freeipa copr will be updated.

**Comment by rcritten** [comment]
*head smack*

Of course. This totally works then, ack.

**Pull request merged**
