### PR TITLE
Use IdM-CI for provisioning

### PR DESCRIPTION
**Pull request by antoniotorresm**
Use IdM-CI to run the performance tests using Red Hat's internal
infrastructure instead of using Vagrant as a provisioner. This allows us
to run the tests without the need of having all the VMs on the same
host, which could cause limitations on the libvirt side in some
situations.

Signed-off-by: Antonio Torres <antorres@redhat.com>

### CODE REVIEW

**Comment by rcritten** [comment]
How difficult do you think it would be to retain support for Vagrant? It makes for isolated development a lot easier.

Perhaps another abstraction layer?

**Comment by antoniotorresm** [comment]
We only need a list of IPs from the provider and this PR abstracts how we SSH into the machines. It might be tricky to handle Vagrant-specific configuration, but I think it's doable. I'll work on it!

**Comment by rcritten** [comment]
I tested that the vagrant provider still works, and it does. I got hung up with the lack of a new release that supports --ad-threads in pamtest.
I did notice that it no longer allocates from the same IP range though. I got three different ranges: 192.168.74.19, 192.168.81,188 and 192.168.169.80.

**Comment by antoniotorresm** [comment]
Vagrant/Libvirt management network netmask is set to 16, so all those IPs belong to the correct range. However I noticed that the network was set to 192.168.3.0/16 instead of 192.168.0.0/16. It shouldn't impact, but I updated it.

**Comment by rcritten** [comment]
I had changeed it to 192.168.3.0 a while back because my local network is 192.168.0.0 so when I'd fire up a perftest it would block my machine from the local lan until I destroyed the libvirt network.
I'd have sworn it used to be /24 but this gives us a LOT more range so it's ok. I guess I didn't pay attention to the IPs as carefully in the past.
If you can switch the base net range back I'll ack this.

**Comment by antoniotorresm** [comment]
With /24 we only have 254 addresses which is a bit low for some of our tests, specially considering the network isn't cleaned up after destroying the machines. Didn't think of the conflict, changed it back to 192.168.3.0.

**Comment by rcritten** [comment]
+1 to 16 vs 24 for the reason you outlined. Thanks for switching it. ack.

**Pull request merged**
